export const FILTER_EVENTS = 'FILTER_EVENTS';
export const SHOW_FILTER_DRAWER = 'SHOW_FILTER_DRAWER';
export const CLOSE_FILTER_DRAWER = 'CLOSE_FILTER_DRAWER';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const SIGN_IN_GOOGLE = 'SIGN_IN_GOOGLE';
export const SIGN_IN_FB = 'SIGN_IN_FB';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';
export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const LOGOUT = 'LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const SHOW_ADD_TEMPLATE_MODAL = 'SHOW_ADD_TEMPLATE_MODAL';
export const CLOSE_ADD_TEMPLATE_MODAL = 'CLOSE_ADD_TEMPLATE_MODAL';

export const CREATE_EVENT = 'CREATE_EVENT';
export const EDIT_EVENT = 'EDIT_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const CLEAR_CURRENT_EVENT = 'CLEAR_CURRENT_EVENT';
export const SET_CURRENT_EVENT = 'SET_CURRENT_EVENT';
export const SHOW_CHANGE_MODAL = 'SHOW_CHANGE_MODAL';
export const CLOSE_CHANGE_MODAL = 'CLOSE_CHANGE_MODAL';
export const GET_ALL_EVENTS = 'GET_ALL_EVENTS';
export const GET_MY_EVENTS = 'GET_MY_EVENTS';
export const GET_BOOKMARKED_EVENTS = 'GET_BOOKMARKED_EVENTS';

export const CREATE_COUPON = 'CREATE_COUPON';
export const EDIT_COUPON = 'EDIT_COUPON';
export const DELETE_COUPON = 'DELETE_COUPON';
export const CLEAR_CURRENT_COUPON = 'CLEAR_CURRENT_COUPON';
export const SET_CURRENT_COUPON = 'SET_CURRENT_COUPON';

export const CREATE_SUBSCRIPTION_PLAN = 'CREATE_SUBSCRIPTION_PLAN';
export const EDIT_SUBSCRIPTION_PLAN = 'END_SUBSCRIPTION_PLAN';
export const DELETE_SUBSCRIPTION_PLAN = 'DELETE_SUBSCRIPTION_PLAN';
export const CLEAR_CURRENT_SUBSCRIPTION_PLAN =
  'CLEAR_CURRENT_SUBSCRIPTION_PLAN';
export const SET_CURRENT_SUBSCRIPTION_PLAN = 'SET_CURRENT_SUBSCRIPTION_PLAN';
export const GET_SUBSCRIPTION_PLANS = 'GET_SUBSCRIPTION_PLANS';
